const EVENT_SERVICE = "EVENT_SERVICE";
const GAME_LOOP_SERVICE = "GAME_LOOP_SERVICE";
const IO_SERVICE = "IO_SERVICE";
const APPLICATION = "APPLICATION";
const DICTIONARY_SERVICE = "DICTIONARY_SERVICE";
const VISUAL_STATUS_RENDERER = "VISUAL_STATUS_RENDERER";
const WORD_DISPLAY_RENDERER = "WORD_DISPLAY_RENDERER";

module.exports = {
  EVENT_SERVICE,
  GAME_LOOP_SERVICE,
  IO_SERVICE,
  APPLICATION,
  DICTIONARY_SERVICE,
  VISUAL_STATUS_RENDERER,
  WORD_DISPLAY_RENDERER,
};
