const EVENT_SERVICE = "EVENT_SERVICE";
const GAME_LOOP_SERVICE = "GAME_LOOP_SERVICE";
const IO_SERVICE = "IO_SERVICE";
const APPLICATION = "APPLICATION";
const DICTIONARY_SERVICE = "DICTIONARY_SERVICE";

module.exports = {
  EVENT_SERVICE,
  GAME_LOOP_SERVICE,
  IO_SERVICE,
  APPLICATION,
  DICTIONARY_SERVICE,
};
